groups:
  - name: alert.rules
    rules:
      - alert: HighCPUUsage
        expr: avg(rate(node_cpu_seconds_total{mode="user"}[2m])) > 0.85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
